
# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    tags:
      - '*'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
#    - name: Step 1 - Set up JDK 11
#      uses: actions/setup-java@v1
#      with:
#        java-version: 11
#        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#        settings-path: ${{ github.workspace }} # location for the settings.xml file
#        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
#        architecture: aarch64 # (x64 or x86) - defaults to x64

    - name: Step 2 - Build with Maven
      run: |
        mvn -T 4 package
        mkdir staging && cp target/expenseTracker*-jar-with-dependencies.jar staging
        cd staging && mv expenseTracker*-jar-with-dependencies.jar expenseTracker.jar

    - name: Step 3 - Persist workflow data as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: github-actions-artifact
        path: staging

    - name: Step 4 - create release
      uses: actions/create-release@v1
      id: create_release
      with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
      env:
          GITHUB_TOKEN: ${{ github.token }}

    - name: Step 5 - upload artifact
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ github.token }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: staging/expenseTracker.jar
          asset_name: expenseTracker-${{ steps.version }}.jar
          asset_content_type: application/gzip
